apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: django-app
  labels:
    app: app-svc
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django-application